name: Build LaTeX document


on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repo
        uses: actions/checkout@v4
      - name: Compile Latex document  
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cookbook.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: cookbook.pdf
     
