name: Build LaTeX document


on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repo
        uses: actions/checkout@v4
      - name: Install LaTeX
        run: sudo apt-get install texlive-full -y
      - name: Compile Latex document  
        run: pdflatex -output-directory=build cookbook.tex
      - name: Move PDF to Specific Directory
        run: mkdir -p pdf_output && mv build/cookbook.pdf pdf_output/
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: pdf_output/cookbook.pdf
     
